name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [windows,linux]
        goarch: [amd64]
        exclude:
          # Exclude i386 on darwin and dragonfly.
          - goarch: 386
            goos: dragonfly
          - goarch: 386
            goos: darwin
          - goarch: 386
            goos: windows
        include:
          # BEGIN Other architectures
          - goos: linux
            goarch: arm64
          - goos: windows
            goarch: arm64
          # END Other architectures
      fail-fast: false

    runs-on: windows-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0

    steps:
      - name: Show workflow information
        id: get_filename
        run: |
          $env:NAME=$env:GOOS+'-'+$env:GOARCH
          $env:ASSET_NAME=$env:NAME
          echo "GOOS:"+$env:GOOS+", GOARCH: "+$env:GOARCH+",GOARM: "+$env:GOARM+", RELEASE_NAME: "+$env:NAME